int InitCodeGeneration(char* filename);
void EmitCode(const char *format, ...);
void EmitPushConstant(int value);
void EmitPushLocal(int index);
void EmitPopPointer(int index);
void EmitPopTemp(int index);
void EmitPopLocal(int index);
void EmitConstructor(char* name, int localFieldsCount);
void EmitFunction(Symbol* symbol);
void EmitCall1(Symbol* symbol);
void EmitCall2(char* className, char* functionName, int argumentCount);
void EmitStartWhile1();
void EmitStartWhile2();
void EmitEndWhile();
void EmitString(char* string);
void EmitLetArray(int arrayAdress);
void EmitAccessArray(int arrayAdress);
void EmitDivide();
void EmitMultiply();
void EmitReturn(Symbol* symbol);
void StopCodeGeneration();